export const players = [
        { name: "Jenn", paid: true, team: "blue", captain: true },
        { name: "Hannah", paid: true, team: "green", captain: true },
        { name: "Khalid", paid: true, team: "yellow", captain: true },
        { name: "Ipek", paid: true, team: "pink", captain: true },
        { name: "Ines", paid: true, team:"yellow" },
        { name: "Sami", paid: true, team:"pink" },
        { name: "Adama", paid: true, team:"yellow" },
        { name: "Aswini", paid: true,team:"green" },
        { name: "Tom", paid: true, team:"blue" },
        { name: "George", paid: true, team:"pink"  },
        { name: "Arshvir", paid: true, team:"green"  },
        { name: "Dylan", paid: true, team:"pink" },
        { name: "Jonathan", paid: true, team:"yellow" },
        { name: "Michael", paid: true, team:"blue" },
        { name: "Jeeven", paid: true, team:"blue" },
        { name: "Michael I", paid: true, team:"green" },
        { name: "Anas", paid: true, team:"yellow"},
        { name: "Tyler", paid: true, team:"yellow" },
        { name: "Samir", paid: true, team:"yellow" },
        { name: "Ibrahim", paid: true, team:"green" },
        { name: "Kaedyn", paid: true, team:"blue" },
        { name: "Azziz", paid: true, team:"pink" },
        { name: "Amber", paid: true, team:"pink" },
        { name: "Seb", paid: true, team:"green" },
        { name: "Kieran", paid: true, team:"blue" },
        { name: "Tia", paid: true, team:"pink" },
        { name: "Francisco", paid: true, team:"pink" },
        { name: "Amelia", paid: false, team:"yellow" },
        { name: "Lys", paid: true, team:"blue" },
        { name: "Felicity", paid: true, team:"green" },
        { name: "Ismail", paid: false, team:"green" },
];
