export const players = [
        { name: "Jenn", paid: true },
        { name: "Hannah", paid: true },
        { name: "Ines", paid: true },
        { name: "Harry", paid: true },
        { name: "Sami", paid: true },
        { name: "Adama", paid: true },
        { name: "Khalid", paid: true },
        { name: "Kieran", paid: false },
        { name: "Aswini", paid: true },
        { name: "Atulya", paid: false },
        { name: "Tom", paid: true },
        { name: "George", paid: true },
        { name: "Arshvir", paid: true },
        { name: "Dylan", paid: true },
        { name: "Will", paid: false },
        { name: "Achish", paid: false },
        { name: "Jonny", paid: true },
        { name: "Michael", paid: true },
        { name: "Jeeven", paid: true },
        { name: "Ipek", paid: true },
        { name: "Michael I", paid: true },
        { name: "EJ", paid: true },
        { name: "Anas", paid: false },
];
